const BAD_REQUEST = 400;
const NOT_FOUND = 404;
const SERVER_ERROR = 500;
const NO_PERMISSION = 403;
const CONFLICT_ERROR = 409;
const UNAUTHORIZED = 401;
const OK_RESPONSE = 200;
const OK_CREATE = 201;


module.exports = {
  BAD_REQUEST,
  NOT_FOUND,
  SERVER_ERROR,
  NO_PERMISSION,
  OK_RESPONSE,
  OK_CREATE,
  CONFLICT_ERROR,
  UNAUTHORIZED
};